#!/bin/bash

set -e

# For every YYYY_MM directory
for dir in $(ls -d */ | grep -E '^[0-9]{4}_[0-9]{2}/'); do
    # Get the year and day from the directory name
    year=$(echo $dir | cut -d'_' -f1)
    day=$(echo $dir | cut -d'_' -f2 | cut -d'/' -f1)
    # strip leading zero
    day_no_leading_zero=${day#0}

    # Check if no input.txt file exists in that directory
    if [ ! -f "${dir}input.txt" ]; then
        # Read the advent of code cookie
        session_cookie=$(<.aoc.cookie)
        # Populate the input.txt
        touch "${dir}input.txt"
        input=$(curl -s --cookie "session=${session_cookie}" https://adventofcode.com/${year}/day/${day_no_leading_zero}/input)
        echo -n "$input" >> "${dir}input.txt"
        echo "Restored ${dir}input.txt"
    else
        echo "File ${dir}input.txt already exists"
    fi
done