#!/bin/bash

set -e

# Check if exactly two arguments are passed
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <day DD>"
    exit 1
fi

# Assign arguments to variables
day=$1
# Add leading zero to day if it's a single digit
day=$(printf "%02d" "$day")

# Run each part separately so we do each from cold start
# That way we get a more accurate timing measurement
uv run -m "${day}.${day}" A
uv run -m "${day}.${day}" B